#ifndef __HVMM_TYPES_H__
#define __HVMM_TYPES_H__

typedef enum {
	HVMM_STATUS_SUCCESS = 0,
	HVMM_STATUS_UNKNOWN_ERROR = -1,
	HVMM_STATUS_UNSUPPORTED_FEATURE = -2,
	HVMM_STATUS_BUSY = -3,
    HVMM_STATUS_BAD_ACCESS = -4,
    HVMM_STATUS_NOT_FOUND = - 5,
} hvmm_status_t;

#endif

